Repository uncrustify/uncrustify, pull requests merged in 2018-09, with the labels that each got.

#1994 Fix returns in macros
  src/chunk_list.cpp
  src/chunk_list.h
  src/combine.cpp
  tests/c.test
  tests/expected/c/00070-return-multi.c
  tests/expected/c/02455-macro-returns.c
  tests/expected/c/02456-macro-returns.c
  tests/expected/cpp/30320-returns.cpp
  tests/expected/cpp/30321-returns.cpp
  tests/expected/cpp/30322-returns.cpp
  tests/expected/cpp/30323-returns.cpp
  tests/expected/cpp/30324-returns.cpp
  tests/expected/cpp/30325-returns.cpp
  tests/expected/cpp/30810-ptr-star.cpp
  tests/input/c/macro-returns.c
  tests/input/cpp/returns.cpp
Labels: C and C++11

#1992 Enforce sp_return_brace on ourselves
  forUncrustifySources.cfg
Labels: Internals

#2002 Don't mark extern prototype as CT_FUNC_CTOR_VAR
  src/combine.cpp
  tests/cpp.test
  tests/expected/cpp/34252-issue_2001.cpp
  tests/input/cpp/issue_2001.cpp
Labels: C and C++11

#2007 Support UTF-8 in CLI output
  tests/cli/test_cli_options.py
Labels: Engineering

#2004 Mark friends as CT_FUNC_PROTO
  src/combine.cpp
  tests/cpp.test
  tests/expected/cpp/34253-friends.cpp
  tests/input/cpp/friends.cpp
Labels: C and C++11

#2010 Fix declaration of chunk_ppa_search
  src/chunk_list.cpp
Labels: Internals

#1986 Namespace option enums
  CMakeLists.txt
  forUncrustifySources.cfg
  src/combine.cpp
  src/enum_flags.h
  src/newlines.cpp
  src/newlines.h
  src/option.cpp
  src/option.h
  src/options.cpp
  src/options.h
  src/space.cpp
  src/tokenize.cpp
  src/uncrustify_types.h
  src/universalindentgui.cpp
Labels: Internals

#2012 Remove broken conversion in test_cli_options.py
  tests/cli/test_cli_options.py
Labels: Engineering

#2013 Use test framework for "sources" tests
  .travis.yml
  CONTRIBUTING.md
  TESTING
  run_tests.bat
  run_tests.sh
  scripts/Run_uncrustify_for_sources.bat
  scripts/Run_uncrustify_for_sources.sh
  tests/CMakeLists.txt
  tests/run_format_tests.py
  tests/run_sources_tests.py
  tests/run_test.py
  tests/test_uncrustify/__init__.py
  tests/test_uncrustify/test.py
  tests/test_uncrustify/utilities.py
Labels: Engineering

#2022 Don't suppress unknown warning for clang
  src/enum_flags.h
Labels: Engineering
